services:
  - type: web
    name: youtube-discord-bot
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python youtube_bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
